Repository ardiansyah-sweng/thesis, pull requests merged in 2020-09, with the labels that each got.

#12 Add function volume kubus
  bangun_ruang.php
Labels: documentation

#11 Menambah Function luaspermukaanpersegipajang
  bangun_ruang.php
Labels: documentation

#8 add function luas permukaan dan volume Limas Segi 3
  .env.example
  app/Console/Commands/ImportDosenCommand.php
  bangun_ruang.php
  database/seeders/DosenSeeder.php
Labels: documentation, enhancement

#26 Add Volume Tabung
  bangun_ruang.php
Labels: documentation

#6 add function luas permukaan kerucut
  bangun_ruang.php
Labels: documentation

#36 menambah function luas jajargenjang
  bangun_ruang.php
Labels: duplicate

#24 Add function keliling balok
  bangun_ruang.php
Labels: documentation

#23 24-Sep-2020 (1700018013) :
  bangun_ruang.php
Labels: documentation

#45 Add luas balok
  bangun_ruang.php
Labels: documentation

#59 revisi penulisan coding untuk rumus luas permukaan tabung
  bangun_ruang.php
Labels: documentation

#68 Add function luasTrapesium
  bangun_ruang.php
Labels: documentation

#58 Add fungsi volume keliling alas pada tabung
  bangun_ruang.php
Labels: enhancement, invalid

#79 add funtion luas permukaan prisma segitiga
  bangun_ruang.php
Labels: documentation

#80 tes Unit Function Volume dan Luas Limas Segitiga
  tests/Unit/BangunRuangTest.php
Labels: enhancement

#67 Add Function Keliling Jajar genjang
  bangun_ruang.php
Labels: documentation
