Repository ardiansyah-sweng/thesis, pull requests merged in 2020-10, with the labels that each got.

#110 menambah function tes_Volume_Setengah_Bola
  app/BangunRuang.php
  tests/Unit/BangunRuangTest.php
Labels: good first issue

#130 Update seeder : Coding query untuk insert ke tabel topik_tugas_akhir
  app/Http/Controllers/LoginController.php
  app/Http/Controllers/TopikController.php
  app/Models/TopikTugasAkhir.php
  database/seeders/DatabaseSeeder.php
  database/seeders/TopikTugasAkhirSeeder.php
  resources/views/topik.blade.php
Labels: question

#137 add luas selimut kerucut
  bangun_ruang.php
Labels: bug

#142 Update rumus luas setengah lingkaran
  bangun_ruang.php
Labels: enhancement
